services:
  redis:
    image: redis:7-alpine
    container_name: django-redis-prod
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-backend
    volumes:
      - static_volume:/app/static
    environment:
      - DEBUG=False
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis
    networks:
      - app-network
    entrypoint: ["/bin/bash", "-c", "cd /app/backend && python manage.py migrate --run-syncdb && exec gunicorn --bind 0.0.0.0:8000 --workers 2 wsgi:application"]
    command: []
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react-frontend-nginx
    ports:
      - "9000:80"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: imresamu/postgis:18-3.6
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  app-network:
    driver: bridge