version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,0.0.0.0,127.0.0.1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: postgres:18.3-trixie  #postgres 13 not supported any more 18.3-trixie latest stable version
    container_name: postgres-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    # Add health check for database readiness
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  app-network:
    driver: bridge
