# Generated by Django 6.0.4 on 2026-04-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkrequest',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkrequest',
            name='owner_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkrequest',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='walkrequest',
            name='dogs',
            field=models.ManyToManyField(blank=True, to='walks.dog'),
        ),
        migrations.AlterField(
            model_name='walkrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
