# Generated by Django 6.0.4 on 2026-04-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_allow_blank_dogs_and_fields'),
        ('walks', '0002_alter_dog_id_alter_walkrequest_id'),
    ]

    operations = [
    ]
