# Generated by Django 6.0.4 on 2026-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_alter_dog_id_alter_walkrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkrequest',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkrequest',
            name='owner_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='walkrequest',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
