# Generated by Django 6.0.4 on 2026-04-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
